export const LOGIN_ACTION = "LOGIN_ACTION";
export const REGISTER_ACTION = "REGISTER_ACTION";
export const ADD_USER_ACTION = "ADD_USER_ACTION";
export const LOGOUT_ACTION = "LOGOUT_ACTION";
export const LOADING = "LOADING";
