export const UPDATE_COMPONENTS = "UPDATE_COMPONENTS";
export const REMOVE_COMPONENT = "REMOVE_COMPONENT";
export const SET_CURRENT_COMPONENT = "SET_CURRENT_COMPONENT";
export const ADD_COMPONENT = "ADD_COMPONENT";
export const LOADING = "LOADING";

export const LOGIN_ACTION = "LOGIN_ACTION";
export const REGISTER_ACTION = "REGISTER_ACTION";
export const ADD_USER_ACTION = "ADD_USER_ACTION";
export const LOGOUT_ACTION = "LOGOUT_ACTION";
