export const UPDATE_COMPONENTS = "UPDATE_COMPONENTS";
export const REMOVE_COMPONENT = "REMOVE_COMPONENT";
export const SET_CURRENT_COMPONENT = "SET_CURRENT_COMPONENT";
export const ADD_COMPONENT = "ADD_COMPONENT";
export const LOADING = "LOADING";
